### ISSUE TITLE
Problem with i18n translations

### ISSUE THREAD

**Issue by mdesanti** [Wolox/codestats#68]
This error has appeared repeated times and is causing some workers to fail.

I18n::InvalidPluralizationData

Stacktrace

```
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:142:in `pluralize'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:40:in `translate'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:45:in `block (2 levels) in translate'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:44:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:44:in `block in translate'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:42:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n/backend/fallbacks.rb:42:in `translate'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:158:in `block in translate'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:154:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:154:in `translate'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/naming.rb:188:in `human'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/errors.rb:437:in `generate_message'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/errors.rb:449:in `normalize_message'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/errors.rb:300:in `add'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/validations/exclusion.rb:11:in `validate_each'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/validator.rb:151:in `block in validate'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/validator.rb:148:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/validator.rb:148:in `validate'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:455:in `public_send'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:455:in `block in make_lambda'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:192:in `block in simple'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/validations.rb:399:in `run_validations!'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
/app/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.5.1/lib/active_model/validations.rb:338:in `valid?'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/validations.rb:58:in `valid?'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/validations.rb:83:in `perform_validations'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/validations.rb:43:in `save!'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:291:in `block in save!'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:291:in `save!'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/active_record_helper.rb:34:in `block in save!'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/transaction.rb:848:in `with_database_metric_name'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent.rb:572:in `with_database_metric_name'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `save!'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/has_many_association.rb:39:in `insert_record'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_association.rb:495:in `block (2 levels) in _create_record'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_association.rb:408:in `replace_on_target'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_association.rb:403:in `add_to_target'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_association.rb:493:in `block in _create_record'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_association.rb:182:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_association.rb:492:in `_create_record'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/has_many_association.rb:187:in `_create_record'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_association.rb:157:in `create!'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/associations/collection_proxy.rb:306:in `create!'
/app/app/managers/branch_manager.rb:10:in `create_or_update'
/app/app/workers/project_branches_retriever.rb:32:in `create_or_update'
/app/app/workers/project_branches_retriever.rb:13:in `block in update_branches'
/app/app/workers/project_branches_retriever.rb:13:in `each'
/app/app/workers/project_branches_retriever.rb:13:in `update_branches'
/app/app/workers/project_branches_retriever.rb:9:in `perform'
/app/app/workers/analyze_github_metrics_status.rb:40:in `fetch_project_branches'
/app/app/workers/analyze_github_metrics_status.rb:15:in `handle_pull_request_status'
/app/app/workers/analyze_github_metrics_status.rb:9:in `perform'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:150:in `execute_job'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-failures-0.4.5/lib/sidekiq/failures/middleware.rb:9:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/logging.rb:30:in `with_context'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:127:in `block in process'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:166:in `stats'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:126:in `process'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:79:in `process_one'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'
/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mdesanti** [comment]
Fixed by @epintos in 4baf3e50ed60f6f518174a88d10eb9140972c870
